version: '3'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn-server
    environment:
      - OVPN_NETWORK=172.18.0.0
      - OVPN_SUBNET=255.255.0.0
      - OVPN_ROUTES=172.18.0.0/16
      - OVPN_MODE=tap 
    volumes:
      - ./data:/etc/openvpn
    ports:
      - "1194:1194/udp"  # Ouvre le port 1194 pour OpenVPN
    cap_add:
      - NET_ADMIN  # Permet à OpenVPN de manipuler les interfaces réseau
    networks:
      - vm-net
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1

networks:
  vm-net:
    external: true
